server:
  port: 9001
  
spring:
  application:
    name: zuul
  
eureka:                                          #请求服务9000
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
      
zuul:                                                
  routes:
    user:                                                #定义模块
      service-id: user-provider                          #用户模块服务的名称
      path: /user/**                                     #url中包含user的请求，可以访问服务名为user_provider的微服务
    goods:                                                #定义模块
      service-id: goods-provider                           #用户模块服务的名称
      path: /goods/**                                      #url中包含goods的请求，可以访问服务名为goods_provider的微服务
    orders:                                                 #定义模块
      service-id: orders-provider                           #用户模块服务的名称
      path: /orders/**                                                                                 